/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-29 10:42:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.onlineshop.utility.DatabaseConnection;
import java.sql.*;
import java.util.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.onlineshop.utility.DatabaseConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Online Shopping System</title>\r\n");
      out.write("        <!-- Importing all ui libs -->\r\n");
      out.write("        <link href=\"assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"assets/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("        <script src=\"js/simpleCart.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/bootstrap-3.1.1.min.js\"></script>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("        <script src=\"jquery-3.2.1.min.js\"></script>\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src='../../../../../../ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>\r\n");
      out.write("        <script src=\"../../../../../../m.servedby-buysellads.com/monetization.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");

            //Checking whether customer in session or not
            if (session.getAttribute("name") != null && session.getAttribute("name") != "") {
        
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"ban-top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"top_nav_left\">\r\n");
      out.write("                    <nav class=\"navbar navbar-default\">\r\n");
      out.write("                        <div class=\"container-fluid\">\r\n");
      out.write("                            <div class=\"navbar-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("                                        data-toggle=\"collapse\"\r\n");
      out.write("                                        data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("                                        aria-expanded=\"false\">\r\n");
      out.write("                                    <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"top_nav_right\">\r\n");
      out.write("                        <div class=\"cart box_1\">\r\n");
      out.write("                            <a href=\"checkout.jsp\"> ");

                                ResultSet resultCount = DatabaseConnection.getResultFromSqlQuery("select count(*) from tblcart where customer_id='" + session.getAttribute("id") + "'");
                                resultCount.next();
                                int count = resultCount.getInt(1);
                            
      out.write("\r\n");
      out.write("                            <h3>\r\n");
      out.write("                                <div class=\"total\">\r\n");
      out.write("                                    <i class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    (\r\n");
      out.write("                                    ");
      out.print(count);
      out.write("\r\n");
      out.write("                                    items )\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </h3>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"javascript:;\" class=\"simpleCart_empty\">My Cart</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"page-head\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h3>Check Out</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"checkout\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h3>My Shopping Bag</h3>\r\n");
      out.write("                ");

                    int index = 0;
                    int paymentId = 101;
                    ResultSet rsCountCheck = DatabaseConnection.getResultFromSqlQuery("select count(*) from tblcart where customer_id='" + session.getAttribute("id") + "'");
                    rsCountCheck.next();
                    int cartItem = rsCountCheck.getInt(1);
                    System.out.println("cartItem  " + cartItem);
                    if (cartItem > 0) {
                
      out.write("\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table table-bordered\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>SR.No</th>\r\n");
      out.write("                                <th>Product</th>\r\n");
      out.write("                                <th>Quantity</th>\r\n");
      out.write("                                <th>MRP(Rs)</th>\r\n");
      out.write("                                <th>Selling Price(Rs)</th>\r\n");
      out.write("                                <th>Total Price(Rs)</th>\r\n");
      out.write("                                <th>Action</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        ");

                            ResultSet totalProduct = DatabaseConnection.getResultFromSqlQuery("select tblproduct.image_name,tblproduct.name,tblcart.quantity,tblcart.mrp_price,tblcart.discount_price,tblcart.total_price,tblcart.product_id from tblproduct,tblcart where tblproduct.id=tblcart.product_id and customer_id='"
                                    + session.getAttribute("id") + "' ");
                            while (totalProduct.next()) {
                                index++;
                        
      out.write("\r\n");
      out.write("                        <tr class=\"rem1\">\r\n");
      out.write("                            <td class=\"invert\">");
      out.print(index);
      out.write("</td>\r\n");
      out.write("                            <td class=\"invert\"><img\r\n");
      out.write("                                    src=\"uploads/");
      out.print(totalProduct.getString(1));
      out.write("\" alt=\"\"\r\n");
      out.write("                                    class=\"pro-image-front\" style=\"width: 150px; height: 100px;\"><br>");
      out.print(totalProduct.getString(2));
      out.write("</td>\r\n");
      out.write("                            <td class=\"invert\">\r\n");
      out.write("                                <div class=\"quantity\">\r\n");
      out.write("                                    <div class=\"quantity-select\">\r\n");
      out.write("                                        <form action=\"UpdateProductQuantity\" method=\"post\">\r\n");
      out.write("                                            <input type=\"hidden\" value=\"");
      out.print(totalProduct.getInt(7));
      out.write("\"\r\n");
      out.write("                                                   name=\"productId\"> <input type=\"number\"\r\n");
      out.write("                                                   name=\"quantity\" value=\"");
      out.print(totalProduct.getInt(3));
      out.write("\"\r\n");
      out.write("                                                   style=\"width: 50px; height: 35px;\">&nbsp;<input\r\n");
      out.write("                                                   type=\"submit\" class=\"btn btn-danger\" value=\"Change\" >\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"invert\"><del>");
      out.print(totalProduct.getString(4));
      out.write("&nbsp;Rs.\r\n");
      out.write("                                </del></td>\r\n");
      out.write("                            <td class=\"invert\">");
      out.print(totalProduct.getString(5));
      out.write("&nbsp;Rs.</td>\r\n");
      out.write("                            <td class=\"invert\">");
      out.print(totalProduct.getString(6));
      out.write("&nbsp;Rs.</td>\r\n");
      out.write("                            <td class=\"invert\"><a\r\n");
      out.write("                                    href=\"removeProductFromCart.jsp?productId=");
      out.print(totalProduct.getInt(7));
      out.write("\"\r\n");
      out.write("                                    onclick=\"return confirm('Are you sure you want to remove this item from cart?');\"><i\r\n");
      out.write("                                        class=\"fa fa-trash\"></i></a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("                        ");

                            double finalBill = 0.0;
                            ResultSet totolAmount = DatabaseConnection.getResultFromSqlQuery("select sum(total_price), sum(mrp_price) from tblcart where customer_id='" + session.getAttribute("id") + "' ");
                            if (totolAmount.next()) {
                                finalBill = totolAmount.getInt(1);
                            }
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>&nbsp;</td>\r\n");
      out.write("                            <td>&nbsp;</td>\r\n");
      out.write("                            <td>&nbsp;</td>\r\n");
      out.write("                            <td>&nbsp;</td>\r\n");
      out.write("                            <td colspan=\"2\"><strong><center>\r\n");
      out.write("                                        Total Amount.:&nbsp;");
      out.print(finalBill);
      out.write("\r\n");
      out.write("                                        Rs.</center></strong>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <script>\r\n");
      out.write("                            $('.value-plus').on('click', function () {\r\n");
      out.write("                                var divUpd = $(this).parent().find('.value'), newVal = parseInt(divUpd.text(), 10) + 1;\r\n");
      out.write("                                divUpd.text(newVal);\r\n");
      out.write("                            });\r\n");
      out.write("\r\n");
      out.write("                            $('.value-minus').on('click', function () {\r\n");
      out.write("                                var divUpd = $(this).parent().find('.value'), newVal = parseInt(divUpd.text(), 10) - 1;\r\n");
      out.write("                                if (newVal >= 1)\r\n");
      out.write("                                    divUpd.text(newVal);\r\n");
      out.write("                            });\r\n");
      out.write("                        </script>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <br> <br> <br>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"GetProductsOrder\" method=\"post\">\r\n");
      out.write("                    <h4>\r\n");
      out.write("                        <font color=\"blue\"><strong>Billing Address</strong></font>\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    ");

                        ResultSet userInfoResult = DatabaseConnection.getResultFromSqlQuery("select * from tblcustomer where id='" + session.getAttribute("id") + "' and name='" + session.getAttribute("name") + "'");
                        if (userInfoResult.next()) {
                    
      out.write("\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Your Name</label> <input type=\"text\" name=\"name\"\r\n");
      out.write("                                                            value=\"");
      out.print(userInfoResult.getString("name"));
      out.write("\" placeholder=\"\"\r\n");
      out.write("                                                            required=\"\" style=\"width: 1135px; height: 40px;\"\r\n");
      out.write("                                                            class=\"form-control\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Phone Number</label> <input type=\"text\" name=\"phone\"\r\n");
      out.write("                                                               value=\"");
      out.print(userInfoResult.getString("phone"));
      out.write("\" placeholder=\"\"\r\n");
      out.write("                                                               required=\"\" style=\"width: 1135px; height: 40px;\"\r\n");
      out.write("                                                               class=\"form-control\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Email Id</label> <input type=\"text\" name=\"email\"\r\n");
      out.write("                                                           value=\"");
      out.print(userInfoResult.getString("email"));
      out.write("\" placeholder=\"\"\r\n");
      out.write("                                                           required=\"\" style=\"width: 1135px; height: 40px;\"\r\n");
      out.write("                                                           class=\"form-control\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Address</label> <input type=\"text\" name=\"address\"\r\n");
      out.write("                                                          value=\"");
      out.print(userInfoResult.getString("address"));
      out.write("\" placeholder=\"\"\r\n");
      out.write("                                                          required=\"\" style=\"width: 1135px; height: 100px;\"\r\n");
      out.write("                                                          class=\"form-control\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Pin Code</label> <input type=\"text\" name=\"pincode\"\r\n");
      out.write("                                                           value=\"");
      out.print(userInfoResult.getString("pin_code"));
      out.write("\" placeholder=\"\"\r\n");
      out.write("                                                           required=\"\" style=\"width: 1135px; height: 40px;\"\r\n");
      out.write("                                                           class=\"form-control\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Select Address Type</label> <select name=\"addressType\"\r\n");
      out.write("                                                                       value=\"\" style=\"width: 1135px; height: 40px;\"\r\n");
      out.write("                                                                       class=\"form-control\">\r\n");
      out.write("                                <option>Home</option>\r\n");
      out.write("                                <option>Office</option>\r\n");
      out.write("                                <option>Commercial</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label>Select Payment Mode</label> <select name=\"payment\"\r\n");
      out.write("                                                                       style=\"width: 1135px; height: 40px;\" class=\"form-control\">\r\n");
      out.write("                                <option>COD</option>\r\n");
      out.write("                                <option>Credit Card</option>\r\n");
      out.write("                                <option>Debit Card</option>\r\n");
      out.write("                                <option>Online Banking</option>\r\n");
      out.write("                                <option>UPI Id</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            ");

                                ResultSet rsPaymentId = DatabaseConnection.getResultFromSqlQuery("select max(payment_id) from tblorders");
                                if (rsPaymentId.next()) {
                                    paymentId = rsPaymentId.getInt("max(payment_id)");
                                    paymentId++;
                                }
                            
      out.write("\r\n");
      out.write("                            <input type=\"text\" name=\"payment_id\" value=\"");
      out.print(paymentId);
      out.write("\" hidden>\r\n");
      out.write("                            <input type=\"submit\" value=\"Buy Products\" class=\"btn btn-success\" onclick=\"return confirm('Are you sure Do you want to buy this order?');\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");

                } else {
                
      out.write("\r\n");
      out.write("                <center>\r\n");
      out.write("                    <strong>Thanks for giving order.</strong>\r\n");
      out.write("                </center>\r\n");
      out.write("                ");

                    if (index == 0) {
                
      out.write("\r\n");
      out.write("                <center>\r\n");
      out.write("                    <strong>There is no item(s) in your Cart.</strong>\r\n");
      out.write("                </center>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                <div class=\"checkout-left\">\r\n");
      out.write("                    <div class=\"checkout-right-basket animated wow slideInRight\" data-wow-delay=\".5s\">\r\n");
      out.write("                        <a href=\"index.jsp\"><span class=\"glyphicon glyphicon-menu-left\" aria-hidden=\"true\"></span>Back To Shopping</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        ");

            } else {
                response.sendRedirect("index.jsp");
            }
        
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
